### ISSUE TITLE
Geoserver Capabilities Request fails in geoserver-123

### ISSUE THREAD

**Issue by kereid** [aodn/issues#22]
See issue https://github.com/aodn/content/issues/256 logged there as it had logged there been in the past, however more recently when it occurred it was classed as a VIT.

**Comment by julian1** [comment]
@xhoenner test?

**Comment by xhoenner** [comment]
> In response to: https://github.com/aodn/content/issues/256#issuecomment-272749597

When clicking on the [OpenLayers](http://geoserver-123.aodn.org.au/geoserver/imos/wms?service=WMS&version=1.1.0&request=GetMap&layers=imos:aatams_sattag_qc_ctd_profile_data&styles=&bbox=132.1974,-65.7303,159.1989,-50.4894&width=768&height=433&srs=EPSG:4326&format=application/openlayers) button for this layers it gives me a 500 error on geoserver-123, however, the same link works perfectly on my PO box. This _data layer uses the 'generic' style so maybe it's been removed from geoserver-123?

![screen shot 2017-01-16 at 11 23 49 am](https://cloud.githubusercontent.com/assets/3443821/21967591/4f86e696-dbde-11e6-92c7-e38614c59a8f.jpg)

**Comment by julian1** [comment]
Just edit the style manually in, ./workspaces/imos/JNDI_aatams_sattag_qc_ctd/aatams_sattag_qc_ctd_profile_data/layer.xml to point at the same style id as _map and that shoud fix it.

**Comment by julian1** [comment]
blocked by https://github.com/aodn/ci-config/issues/17

**Comment by julian1** [comment]
now fixed!
