### ISSUE TITLE
Cannot download any gridded collections in SYSTEST

### ISSUE THREAD

**Issue by kereid** [aodn/issues#25]
Steps to reproduce:

Add any gridded collection to the map proceed to step 3, try to download netCDF

What should happen:

Download works

What does happen:

See error:

Error! The server response was: 'Internal Server Error'
Unable to create subsetting job. Please re-check the parameters you provided and try again.

**Comment by jonescc** [comment]
I'll look at this

**Comment by jonescc** [comment]
Actually @anguss00 is starting up the EC2 instance and reprovisioning setting the DNS correctly.  He'll let you know when its up.

**Comment by kereid** [comment]
Thanks :-)

**Comment by anguss00** [comment]
Should be good to go now @kereid
