### ISSUE TITLE
Link from email for error does not work

### ISSUE THREAD

**Issue by kereid** [aodn/issues#27]
SYSTEST

Steps to reproduce:

Execute a job that will fail and wait for email, when error email recieved click the link

What should happen:

Taken to page where is states why the job failed

What does happen:

Taken to a page and see this error

Host for address 'http://geoserver-wps-systest-aws.aodn.org.au/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionStatus&executionId=b4979df3-3b3e-45e8-9773-6dfcaf479c3d' not allowed

**Comment by anguss00** [comment]
I'll look at this @kereid. Assuming a VIT as blocking testing

**Comment by kereid** [comment]
@anguss00 I could technically continue testing but I would say this is a showstopper as we get many failed emails and if people can't see why they are failing then it shouldn't be released..

**Comment by anguss00** [comment]
Fixed @kereid, try now!
